# Generated by Django 4.2.2 on 2023-07-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_remove_recursoshumanos_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='RecursosHumanos',
        ),
        migrations.DeleteModel(
            name='Vendedores',
        ),
    ]
