# Generated by Django 4.2.2 on 2023-07-08 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App1', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('matemática', 'Matemática'), ('física', 'Física'), ('química', 'Química'), ('especialidad', 'Especialidad')], default='se ofrece', max_length=15)),
                ('materia', models.CharField(choices=[('matemática', 'Matemática'), ('física', 'Física'), ('química', 'Química'), ('especialidad', 'Especialidad')], default='matemática', max_length=15)),
                ('nivel', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('telefonoContacto', models.IntegerField()),
                ('emailContacto', models.EmailField(max_length=254)),
                ('imagenAlusiva', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario', '-fechaPublicacion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fechaComentario', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='App1.clases')),
            ],
            options={
                'ordering': ['-fechaComentario'],
            },
        ),
    ]
