# Generated by Django 4.2.2 on 2023-07-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_alter_clases_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clases',
            name='tipo',
            field=models.CharField(choices=[('se ofrece', 'Se Ofrece'), ('se necesita', 'Se Necesita')], default='se ofrece', max_length=15),
        ),
    ]
